// USING DIRECTIVE - PROGRAM HAS ACCESS TO NAMESPACE
// SYSTEM - ACCESS COMMONLY USED CLASSES AND USE TYPES
using System;

// ARBITRARILY NAMED - BLUEPRINT FOR CREATING OBJECTS
class One
{
//  STATIC - CAN CALL METHOD WITHOUT INSTANCE
//  VOID - METHODCALL DOES NOT RETURN VALUE
    static void Main() // FIRST METHOD INVOKED 
    {
        // CONSOLE - SYSTEM NAMESPACE CLASS
        // WRITELINE - METHOD TO OUTPUT STRING ARGUMENT TO CONSOLE
        Console.WriteLine("MAIN > CODE BLOCK > WRITELINESTRING");
        
    }
}