// CREATE SOMETHING GAME-LIKE AND FUN
// CONSIDER HOW TO MAKE SOMETHING SIMPLE ALONG THE LINES OF A PET SIMULATOR
// CONSIDER HOW TO USE ASYNC AWAIT
    // PET NEEDS TO EAT AND YOU HAVE TO COOK A FOOD ITEM
    // IF THE USER WAITS TOO LONG TO COOK THE FOOD ITEM - IT BURNS
    // IF THE USER WAITS NOT LONG ENOUGH- THE FOOD ITEM IS RAW AND UNEDIBLE
    // IF THE USER WAITS A SPECIFIED AMOUNT OF TIME - THE FOOD IS COOKED JUST RIGHT AND CAN BE FED 