// CREATE A MENU THAT CAN CREATE DIFFERENT DATA TYPES
// ASK USER FOR INPUT
// ASK USER IF KEY AND VALUE
// ASK USER IF VALUE FOR SPECIFIED KEY
// DETECT NON-UNIQUE ENTRIES
// CREATE A USERNAME & PASSWORD & EMAIL ADDRESS