// EXPLORE ASYCHRONOUS PROGRAMMING
// USE AN API 
// CREATE A WINDOW INSTEAD OF PRINTING TO THE CONSOLE
// SHOW THE CURRENT WEATHER IN REAL-TIME
// -TEMPERATURE 
// -WIND
// -MOON PHASE 
// -SUNSET
// -SUNRISE

// CHALLENGE: DETERMINE IDEAL BOATING CONDITIONS
